[build]
command = "npm install"
functions = "netlify/functions"
publish = "public"

[[redirects]]
from = "/api/student/:studentId/courses"
to = "/.netlify/functions/student-courses?studentId=:studentId"
status = 200

[[redirects]]
from = "/api/course/:courseCode/students"
to = "/.netlify/functions/course-students?courseCode=:courseCode"
status = 200

[[redirects]]
from = "/api/graph-data"
to = "/.netlify/functions/graphData"
status = 200

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/signin.html"
status = 200

[context.production.environment]
NEO4J_URI = "neo4j+s://ce7d6f3d.databases.neo4j.io"
NEO4J_USER = "ce7d6f3d"
